# Copyright (c) The dgc.network
# SPDX-License-Identifier: Apache-2.0

version: "2.1"

services:
  dgc-contract-api:
    image: dgc-contract-api
    container_name: dgc-contract-api
    volumes:
      - .:/project
    expose:
      - 9001
    ports:
      - 9001:9001
    #ports:
    #  - '0.0.0.0:9001:8000'
    entrypoint: "bash -c \"\
      cd /project/api && \
      cargo build && \
      tail -f /dev/null \
      \""
    build:
      context: ./api/
    environment:
      RUST_BACKTRACE: 1
      ROCKET_ADDRESS: "0.0.0.0"
      ROCKET_PORT: 9001
      VALIDATOR_URL: tcp://validator:9004
      #DATABASE_URL: postgres://pike:pike@pike-db:5432/pike

  validator:
    image: hyperledger/sawtooth-validator:latest
    container_name: sawtooth-validator
    volumes:
      - .:/project
    expose:
      - 9704
    ports:
      - "9704:9704"
    entrypoint: "bash -c \"\
        sawadm keygen && \
        sawtooth keygen && \
        mkdir -p /project/keys && \
        cp /root/.sawtooth/keys/* /project/keys &&
        sawset genesis  -k /etc/sawtooth/keys/validator.priv && \
        sawset proposal create \
          -k /etc/sawtooth/keys/validator.priv \
          -o config.batch \
          sawtooth.swa.administrators=$$(cat project/keys/root.pub) \
          sawtooth.consensus.algorithm.name=Devmode \
          sawtooth.consensus.algorithm.version=0.1 && \
        sawadm genesis config-genesis.batch config.batch && \
        sawtooth-validator -vv \
          --endpoint tcp://validator:9705 \
          --bind component:tcp://eth0:9704 \
          --bind network:tcp://eth0:9705 \
          --bind consensus:tcp://eth0:5050 \
        \""

  rest-api:
    image: hyperledger/sawtooth-rest-api:latest
    container_name: sawtooth-rest-api
    expose:
      - 9708
    ports:
      - "9708:9708"
    entrypoint: sawtooth-rest-api --connect tcp://validator:9704 --bind rest-api:9708 -vv

  shell:
    image: hyperledger/sawtooth-shell:latest
    container_name: sawtooth-shell
    entrypoint: "bash -c \"\
        sawtooth keygen && \
        tail -f /dev/null \
        \""

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:latest
    container_name: sawtooth-settings-tp
    entrypoint: settings-tp -vv --connect tcp://validator:9704

  devmode-rust:
    image: hyperledger/sawtooth-devmode-engine-rust:latest
    container_name: sawtooth-devmode-engine-rust
    depends_on:
      - validator
    command: |
        devmode-engine-rust -v --connect tcp://validator:5050
    stop_signal: SIGKILL

  dgc-contract-tp:
    image: dgc-contract-tp:${ISOLATION_ID}
    container_name: dgc-contract-tp
    entrypoint: "bash -c \"\
        cd /project/tp/ && \
        cargo build && \
        dgc-contract-tp -vv -C tcp://validator:9704 \
        \""
    volumes:
      - .:/project
    build:
      context: tp

  dgc-contract-cli:
    image: dgc-contract-cli:${ISOLATION_ID}
    container_name: dgc-contract-cli
    volumes:
      - .:/project
      - ./keys:/root/.sawtooth/keys
    entrypoint: "bash -c \"\
      cargo build && \
      tail -f /dev/null \
      \""
    build:
      context: cli
