# Copyright (c) The dgc.network
# SPDX-License-Identifier: Apache-2.0

version: "2.1"

services:
  validator:
    image: hyperledger/sawtooth-validator:latest
    container_name: smart-validator
    volumes:
      - .:/project
    expose:
      - 9704
    ports:
      - "9704:9704"
    entrypoint: |
        bash -c "
        sawadm keygen &&
        sawtooth keygen &&
        mkdir -p /project/keys && \
        cp /root/.sawtooth/keys/* /project/keys &&
        sawset genesis -k /etc/sawtooth/keys/validator.priv &&
        sawset proposal create \
          -k /etc/sawtooth/keys/validator.priv \
          sawtooth.swa.administrators=$$(cat project/keys/root.pub) \
          sawtooth.consensus.algorithm.name=Devmode \
          sawtooth.consensus.algorithm.version=0.1 \
          -o config.batch && \
        sawadm genesis config-genesis.batch config.batch && \
        sawtooth-validator -vv \
          --endpoint tcp://validator:9705 \
          --bind component:tcp://eth0:9704 \
          --bind network:tcp://eth0:9705 \
          --bind consensus:tcp://eth0:5050"

  rest-api:
    image: hyperledger/sawtooth-rest-api:latest
    container_name: smart-sawtooth-rest-api
    expose:
      - 9708
    ports:
      - "9708:9708"
    entrypoint: sawtooth-rest-api --connect tcp://validator:9704 --bind rest-api:9708 -vv

  shell:
    image: hyperledger/sawtooth-shell:latest
    container_name: smart-shell
    entrypoint: |
        bash -c "
        sawtooth keygen &&
        tail -f /dev/null"

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:latest
    container_name: smart-settings-tp
    entrypoint: settings-tp -vv --connect tcp://validator:9704

  devmode-rust:
    image: hyperledger/sawtooth-devmode-engine-rust:latest
    container_name: sawtooth-devmode-engine-rust
    depends_on:
      - validator
    command: |
        devmode-engine-rust -v --connect tcp://validator:5050
    stop_signal: SIGKILL

  smart-tp:
    build:
      context: .
      dockerfile: tp/Dockerfile-installed-${DISTRO}
    image: sawtooth-smart-tp:${ISOLATION_ID}
    container_name: sawtooth-smart-tp
    depends_on:
      - validator
    entrypoint: sawtooth-smart -vv --connect tcp://validator:9704

  smart-cli:
    build:
      context: .
      dockerfile: cli/Dockerfile-installed-${DISTRO}
    image: sawtooth-smart-cli:${ISOLATION_ID}
    container_name: smart-cli
    volumes:
      - .:/project
      - ./keys:/root/.sawtooth/keys
    entrypoint: tail -f /dev/null

  intkey_multiply:
    build:
      context: .
      dockerfile: example/intkey_multiply/processor/Dockerfile-scar
    image: intkeym-scar:${ISOLATION_ID}
