# Copyright (c) The dgc.network
# SPDX-License-Identifier: Apache-2.0

# docker build -f tp/Dockerfile-installed-xenial -t dgc-contract-tp .

# -------------=== dgc contract tp build ===-------------

FROM ubuntu:xenial as dgc-contract-tp-builder

ENV VERSION=AUTO_STRICT

RUN apt-get update \
 && apt-get install -y \
 curl \
 gcc \
 git \
 libssl-dev \
 libzmq3-dev \
 pkg-config \
 python3 \
 unzip

# For Building Protobufs
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y \
 && curl -OLsS https://github.com/google/protobuf/releases/download/v3.5.1/protoc-3.5.1-linux-x86_64.zip \
 && unzip protoc-3.5.1-linux-x86_64.zip -d protoc3 \
 && rm protoc-3.5.1-linux-x86_64.zip

ENV PATH=$PATH:/protoc3/bin  \
    CARGO_INCREMENTAL=0
RUN /root/.cargo/bin/cargo install cargo-deb

COPY . /project

WORKDIR /project/tp

RUN export VERSION=$(../bin/get_version) \
 && sed -i -e s/version.*$/version\ =\ \"${VERSION}\"/ Cargo.toml \
 && /root/.cargo/bin/cargo deb --deb-version $VERSION

# -------------=== dgc contract tp build ===-------------

FROM ubuntu:xenial

COPY --from=dgc-contract-tp-builder /project/tp/target/debian/dgc-contract-tp*.deb /tmp

RUN apt-get update \
 && dpkg -i /tmp/dgc-contract-tp*.deb || true \
 && apt-get -f -y install
