#!/bin/bash

# Copyright (c) The dgc.network
# SPDX-License-Identifier: Apache-2.0

set -e

user="sawtooth"
group="sawtooth"

if ! getent group $group > /dev/null; then
    addgroup --quiet --system $group
fi

if ! getent passwd $user > /dev/null; then
    adduser --quiet --system --ingroup $group $user
fi
