# Copyright (c) The dgc.network
# SPDX-License-Identifier: Apache-2.0

version: "2.1"

services:
  sabre-docs:
    image: sabre-docs:${ISOLATION_ID}
    container_name: sabre-docs
    volumes:
      - ..:/project
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: "bash -c \"\
      cd /project/cli && \
      cargo build && \
      cd /project/docs && \
      ./bin/generate_cli_output && \
      make html
      \""
