# Copyright (c) The dgc.network
# SPDX-License-Identifier: Apache-2.0

# docker build -f api/Dockerfile-installed-bionic -t dgc-contract-api .

# -------------=== dgc api build ===-------------

FROM ubuntu:bionic as dgc-contract-api-builder

ENV VERSION=AUTO_STRICT

RUN apt-get update \
 && apt-get install -y \
 curl \
 gcc \
 git \
 libpq-dev \
 libssl-dev \
 libzmq3-dev \
 pkg-config \
 python3 \
 unzip

# For Building Protobufs
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y \
 &&  /root/.cargo/bin/rustup default nightly \
 && curl -OLsS https://github.com/google/protobuf/releases/download/v3.5.1/protoc-3.5.1-linux-x86_64.zip \
 && unzip protoc-3.5.1-linux-x86_64.zip -d protoc3 \
 && rm protoc-3.5.1-linux-x86_64.zip

ENV PATH=$PATH:/protoc3/bin
RUN /root/.cargo/bin/cargo install cargo-deb

COPY . /project

WORKDIR /project/api

RUN export VERSION=$(../../../bin/get_version) \
 && sed -i -e "0,/version.*$/ s/version.*$/version\ =\ \"${VERSION}\"/" Cargo.toml \
 && /root/.cargo/bin/cargo deb --deb-version $VERSION

# -------------=== dgc api docker build ===-------------

FROM ubuntu:bionic

COPY --from=dgc-contract-api-builder /project/api/target/debian/dgc-contract-api*.deb /tmp

RUN apt-get update \
 && dpkg -i /tmp/dgc-contract-api*.deb || true \
 && apt-get -f -y install

ENTRYPOINT ["tail", "-f", "/dev/null"]
