# Copyright (c) The dgc.network
# SPDX-License-Identifier: Apache-2.0

FROM ubuntu:bionic

RUN apt-get update \
  && apt-get install -y -q \
       apache2 \
       curl \
       vim \
  && apt-get clean \
  && rm -r /var/lib/apt/lists/*

WORKDIR /var/www

RUN curl \
      -s https://codeload.github.com/swagger-api/swagger-ui/tar.gz/v3.6.0 \
      -o swagger-ui.tar.gz
RUN tar xfz swagger-ui.tar.gz
RUN mv swagger-ui-3.6.0/dist/* /var/www/html/

RUN sed -ibak \
      's#http://petstore.swagger.io/v2/swagger.json#http://localhost:9001/openapi.yaml#' \
      /var/www/html/index.html

EXPOSE 80

CMD ["apachectl", "-D", "FOREGROUND"]
